version: 0.2
#env:
  #parameter-store:
    #ARTIFACTORY_API_KEY: AKCp5fTQsWeHCJ2AiV2gHpjZAWvyfyvDoG2h9og1AhBW6tCgitTiQwpaZ7ryB8JbXBj2VxFER
phases:
  install:
    commands:
      - echo Entering install phase...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - docker info
      - wget https://jcenter.bintray.com/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.tar.gz 
      - tar xzvf apache-maven-3.3.9-bin.tar.gz -C /opt/
      - export PATH=/opt/apache-maven-3.3.9/bin:$PATH
      - wget https://dl.bintray.com/jfrog/jfrog-cli-go/1.12.1/jfrog-cli-linux-amd64/jfrog
      - chmod +x jfrog

  pre_build:
    commands:
      - echo Entering pre_build phase...
      - jfrog rt config --url http://172.31.26.21:8081/artifactory --user admin --apikey AKCp5fTQsWeHCJ2AiV2gHpjZAWvyfyvDoG2h9og1AhBW6tCgitTiQwpaZ7ryB8JbXBj2VxFER
      #- sed -i -e 's|ARTIFACTORY_USER|admin|g' settings.xml && sed -i -e 's|ARTIFACTORY_PASSWORD|AKCp5fTQsWeHCJ2AiV2gHpjZAWvyfyvDoG2h9og1AhBW6tCgitTiQwpaZ7ryB8JbXBj2VxFER|g' settings.xml && sed -i -e 's|ARTIFACTORY_MVN_REPO|maven-pipeline-dev-local|g' settings.xml
  build:
    commands:
      #- echo Entering build phase...
      #- echo Build started on `date`
      #- mvn install -Dmaven.test.skip=true
      - jfrog rt dl maven-pipeline-dev-local/target/
        
  post_build:
    commands:
      - docker build -t 172.31.26.21:8081/docker-local/guestbook-microservices-k8s/guestbook-service:10 .
      - jfrog rt dp 172.31.26.21:8081/docker-local/guestbook-microservices-k8s/guestbook-service:10 docker-local --build-name=test-pipeline --build-number=10
      - jfrog rt bp test-pipeline 10


